language: go
env:
  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
  global:
    secure: Y9aTqi9M4feJ5NORAIZqkILS7O9rSEW8g5kKjabJOsz635H5HryP8HCQKR7PZt81dfXEIR+Ox3k26rgml5fzPUAg+aXp5rSCM0HuHqIQlY7Yixuv2aMP2mVjll/SrUEAonXUm3GLWprZs7YtW72RNKLREvrZfal++Or8n327qfM9O19tmsUT9ADES8H6WhPHt2KVUJ+JtmAtTONAZru3c9jVlcRiR33Mx/wwonXosP2nm0QxuTeiiQtQE8fM0bHvQl/WSLvcG6+SqmBkuITWL4eNRoTeDACcY+Ev9f14G+4fi+8z6RQ3aSDmbO/6DYFinLWA8Y3LbbcKEVS0iCml3uPHoBcOw8s7arMFu4pUCV8ag/6xXPjNRXEZl+DaF4QNp9VWabK6fnuKuCc8Wl5iLuguZe9GSz/3MPKbK6b3C+dQBwOv729uxqmO07VL/y4EpdE/FF/pSuBfZKEBxMT2dYX283cnz9YJkdakM+dEW/Nqsa1rGwoTbo+EWhNK/IbX3tyASFvkzc286GBZMLgzMpYwyyihmd+CKq7QzXK5faCsVWAVJMacdSwVA9arzvnWIqVFPQjqMt+rskwkh1lOo06wSNfu4sOPIaKPa3ekdCxMxMg6gcck3RiJUC4tF2Mm6vHs+2tm8YExmf690eGlZmXKRp0uKLqDfHroyedNNHc=
sudo: required
go:
- 1.9.4
- tip
install:
- go get golang.org/x/tools/cmd/cover github.com/mattn/goveralls
script:
- make
- make coverage-report
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key:
    secure: TadgNCcj0JXu33Pu77U4DHCnBdKrmDJg+TivMZsmkRA7uXxzTLgvPyuR9drH2HJ1THHtA6BGRKs8uUm50JC8KLQTMwdDm2Dknb6JM71yO10jSnmM2wfuTjdNjVk89muDkoYaz7VxDK85dKdj1A+WavDLYmApEJJut3KmugQAu5SRNO72FVz//hjaJfEcAV8AxIXPrKJvk/jawL3KSthMtRG4AF69O9jhKAs5+GIojyjsHgI1Ovdew8S/ERDZTnOLDksROJwG5Cm6EaP2OFi0LxnGOhXI6Ht38VGGBepwWHtFNgxs/vUsJFVKCU13ezmBV9WTU07u3rdr+Rd2Jt8a/0KqRkmxFR97vuYz8DnhptAPodyLd+xMlmZ54Bq2Q9E9XmmoA1UX3e8x2zTfEOSp/3hCO/E3RhLX4pjGnzoDK42VVLPA9PTUisPhO0UpQTn7bAstUnj48x+3gDdMw0EGaYMSzHmcDV9iuXCHj2iUR8Puc9kA+OSPg/WnxIN6S3h7qNpsdoVRMVSEXv2s/fkbcnzMI2t2/hgvqWzYYwwW0riUM25kfkCwopvIOZk+1aI/W6auRzF6wdfuHxe2Tb2qOz0CPsS5yu4rSd4dxqhAyF/d+MPKfSFqX5uI4UifLHuvfHUUTE09RBAParsSAooSoFOaGtya1SDBpwLDwlRD/RQ=
  file:
  - build/darwin_amd64.zip
  - build/linux_386.zip
  - build/linux_amd64.zip
  - build/windows_amd64.zip
  - build/sloppose_darwin_amd64
  - build/sloppose_linux_386
  - build/sloppose_linux_amd64
  - build/sloppose_windows_amd64.exe
  skip_cleanup: true # prevent file deletion
  on:
    repo: sloppyio/sloppose
    tags: true
